export { default as Navbar } from "../components/navbar/navbar";
export { default as Filter } from "../components/filter/filter";
export { default as Carousel } from "../components/carousel/carousel";
export { default as WhyBlock } from "../components/why_block/why_block";
export { default as Footer } from "../components/footer/footer";
export { default as ContactForm } from "../components/contact_form/contact_form";
export { default as BackgroundHeader } from "../components/background_header/background_header";
export { default as PropertyDetailsBody } from "../components/property_details/property_details_body";
export { default as PropertyDetailsHeader } from "../components/property_details/property_details_header";
